table 'dbo_gold fact_financials'
	lineageTag: 233b3805-753e-41ce-bf17-4cfe6b2e3358

	measure Revenue =
			
			CALCULATE(
			    SUM('dbo_gold fact_financials'[value]),
			    'dbo_gold fact_financials'[metric_name] = "revenue"
			)
		lineageTag: aa7c3490-2c95-4d46-89b5-bf0a1a56edd2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column company_name
		dataType: string
		lineageTag: ad5eda68-c043-476d-98fa-e9fa4cd12bce
		summarizeBy: none
		sourceColumn: company_name

		annotation SummarizationSetBy = Automatic

	column cik
		dataType: string
		lineageTag: 383e566b-b79a-434e-83dd-848ce821e9c9
		summarizeBy: none
		sourceColumn: cik

		annotation SummarizationSetBy = Automatic

	column metric_name
		dataType: string
		lineageTag: 6b7540db-c3c5-4dee-a732-fb2012814616
		summarizeBy: none
		sourceColumn: metric_name

		annotation SummarizationSetBy = Automatic

	column concept
		dataType: string
		lineageTag: 34c68d29-e1a9-4b27-952c-ef3d8b1ccee5
		summarizeBy: none
		sourceColumn: concept

		annotation SummarizationSetBy = Automatic

	column period_end
		dataType: dateTime
		formatString: Long Date
		lineageTag: 481456de-c93c-41f2-b062-76c19f691639
		summarizeBy: none
		sourceColumn: period_end

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column period_start
		dataType: dateTime
		formatString: Long Date
		lineageTag: 701cb9b3-248a-4bd4-aeab-652ea80a35c1
		summarizeBy: none
		sourceColumn: period_start

		variation Variation
			isDefault
			relationship: 9103bdf5-b944-4fac-937e-b6ca1a4f6b6d
			defaultHierarchy: LocalDateTable_ea7d420b-6680-4dcb-aff0-995f72be69b3.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column form
		dataType: string
		lineageTag: c3dacfe6-f204-48e1-95e6-fe2e5625d546
		summarizeBy: none
		sourceColumn: form

		annotation SummarizationSetBy = Automatic

	column filed
		dataType: dateTime
		formatString: Long Date
		lineageTag: 147f78be-9d69-4851-81a2-885cd5936045
		summarizeBy: none
		sourceColumn: filed

		variation Variation
			isDefault
			relationship: 2842137b-2e9e-4e80-8c6a-f48f7b118797
			defaultHierarchy: LocalDateTable_0ce83656-1cd2-4d14-9739-4236dd5ed8b2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column value
		dataType: double
		lineageTag: bbcf6e8f-786c-4c61-917d-7ed4f9bebff3
		summarizeBy: sum
		sourceColumn: value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column unit
		dataType: string
		lineageTag: 07be07fa-f027-4ee1-9320-79a9933ce9c6
		summarizeBy: none
		sourceColumn: unit

		annotation SummarizationSetBy = Automatic

	column period_type
		dataType: string
		lineageTag: 32997438-b90c-4d56-9f9b-81277e67692a
		summarizeBy: none
		sourceColumn: period_type

		annotation SummarizationSetBy = Automatic

	column fiscal_year
		dataType: int64
		formatString: 0
		lineageTag: be1058db-9bf4-4366-8055-31e2e0cca3d5
		summarizeBy: sum
		sourceColumn: fiscal_year

		annotation SummarizationSetBy = Automatic

	column fiscal_quarter
		dataType: int64
		formatString: 0
		lineageTag: d7891a80-5d2d-4f0f-b159-2cc7d862c09c
		summarizeBy: sum
		sourceColumn: fiscal_quarter

		annotation SummarizationSetBy = Automatic

	partition 'dbo_gold fact_financials' = m
		mode: import
		source =
				let
				    Source = Sql.Database("sql-edgar-analytics.database.windows.net", "edgar-analytics"),
				    dbo_gold_fact_financials = Source{[Schema="dbo_gold",Item="fact_financials"]}[Data]
				in
				    dbo_gold_fact_financials

	annotation PBI_ResultType = Table

